### ISSUE TITLE
Logistics access to Logistics role.

### ISSUE THREAD

**Issue by chrisleaptrott** [chrisleaptrott/Liberation#4]
Production settings and logistics access needs to be added to the Logistics Lead role to ensure that people can get on and do that without issue.

**Comment by milivojm** [comment]
Can we also hide it for everyone else because having a sidebar is a bit annoying for players who don't care about logistics (on larger ops)?

**Comment by chrisleaptrott** [comment]
Well, the sidebar is only there in base, so I don't think its too obtrusive. I'd leave it just so people can get a snapshot at what's going on, alertness, CIV demeanor.

**Comment by milivojm** [comment]
Let's do it the way only Keystone and Commander can have a self action which opens the dialog screen showing latest resource amount. That way we will remove the sidebar.
